import {
  SwitchCombatant, Retreat, Rest, Struggle, Slash, Thrust, Eviscerate, Punch, Strike, ShootArrow,
  Tripleshot, ShootFlamingArrow, Cleave, Flurry, Uppercut, MagicMissile, ArcaneBlast, LesserHeal,
  Cleanse, DrainLife, DarkOrb, Bite, Fireball, Inferno, LightningBolt, IceShard, IceWall, HailStorm,
  Shockwave, Siphon, Earthquake, ShootWeb, Pounce, Block, Brace, Hide, VineLash, Shapeshift,
  CallOfSterben, Bless, Curse, Roar, Rage, Howl, ChannelMagic, Hex, ShootBullet, Barrage, Fly,
  CastShadow, ExposeWeakness, GuardBreak, AbsorbSoul, Impale, FlashFreeze, ThrowPosionedKnife,
  SetBearTrap, ThrowNet, ThrowSmokeBomb, DrinkHealthPotion, DrinkStaminaPotion, DrinkMagicPotion,
  UseAntidote, UseAloeRemedy, UseBandage, UseParalysisTonic, DrinkKurtussBrewOfMadness
} from "../abilities.js";

export const abilityRegistry = {
  "switch combatant": (config) => { return new SwitchCombatant(config); },
  "retreat": (config) => { return new Retreat(config); },
  "rest": (config) => { return new Rest(config); },
  "struggle": (config) => { return new Struggle(config); },
  "slash": (config) => { return new Slash(config); },
  "thrust": (config) => { return new Thrust(config); },
  "eviscerate": (config) => { return new Eviscerate(config); },
  "punch": (config) => { return new Punch(config); },
  "strike": (config) => { return new Strike(config); },
  "shoot arrow": (config) => { return new ShootArrow(config); },
  "triple shot": (config) => { return new Tripleshot(config); },
  "shoot flaming arrow": (config) => { return new ShootFlamingArrow(config); },
  "cleave": (config) => { return new Cleave(config); },
  "flurry": (config) => { return new Flurry(config); },
  "uppercut": (config) => { return new Uppercut(config); },
  "magic missile": (config) => { return new MagicMissile(config); },
  "arcane blast": (config) => { return new ArcaneBlast(config); },
  "lesser heal": (config) => { return new LesserHeal(config); },
  "cleanse": (config) => { return new Cleanse(config); },
  "drain life": (config) => { return new DrainLife(config); },
  "dark orb": (config) => { return new DarkOrb(config); },
  "bite": (config) => { return new Bite(config); },
  "fireball": (config) => { return new Fireball(config); },
  "inferno": (config) => { return new Inferno(config); },
  "lightning bolt": (config) => { return new LightningBolt(config); },
  "ice shard": (config) => { return new IceShard(config); },
  "ice wall": (config) => { return new IceWall(config); },
  "hail storm": (config) => { return new HailStorm(config); },
  "shockwave": (config) => { return new Shockwave(config); },
  "siphon": (config) => { return new Siphon(config); },
  "earthquake": (config) => { return new Earthquake(config); },
  "shoot web": (config) => { return new ShootWeb(config); },
  "pounce": (config) => { return new Pounce(config); },
  "block": (config) => { return new Block(config); },
  "brace": (config) => { return new Brace(config); },
  "hide": (config) => { return new Hide(config); },
  "vine lash": (config) => { return new VineLash(config); },
  "shapeshift": (config) => { return new Shapeshift(config); },
  "call of sterben": (config) => { return new CallOfSterben(config); },
  "bless": (config) => { return new Bless(config); },
  "curse": (config) => { return new Curse(config); },
  "roar": (config) => { return new Roar(config); },
  "rage": (config) => { return new Rage(config); },
  "howl": (config) => { return new Howl(config); },
  "channel magic": (config) => { return new ChannelMagic(config); },
  "hex": (config) => { return new Hex(config); },
  "shoot bullet": (config) => { return new ShootBullet(config); },
  "barrage": (config) => { return new Barrage(config); },
  "fly": (config) => { return new Fly(config); },
  "cast shadow": (config) => { return new CastShadow(config); },
  "expose weakness": (config) => { return new ExposeWeakness(config); },
  "guard break": (config) => { return new GuardBreak(config); },
  "absorb soul": (config) => { return new AbsorbSoul(config); },
  "impale": (config) => { return new Impale(config); },
  "flash freeze": (config) => { return new FlashFreeze(config); },
  
  "throw posioned knife": (config) => { return new ThrowPosionedKnife(config); },
  "set bear trap": (config) => { return new SetBearTrap(config); },
  "throw net": (config) => { return new ThrowNet(config); },
  "throw smoke bomb": (config) => { return new ThrowSmokeBomb(config); },
  "drink health potion": (config) => { return new DrinkHealthPotion(config); },
  "drink stamina potion": (config) => { return new DrinkStaminaPotion(config); },
  "drink magic potion": (config) => { return new DrinkMagicPotion(config); },
  "use antidote": (config) => { return new UseAntidote(config); },
  "use aloe remedy": (config) => { return new UseAloeRemedy(config); },
  "use bandage": (config) => { return new UseBandage(config); },
  "use paralysis tonic": (config) => { return new UseParalysisTonic(config); },
  "drink kurtuss brew of madness": (config) => { return new DrinkKurtussBrewOfMadness(config); },
};