import {
  Dagger, ShortSword, Spear, BlacksmithHammer, Handaxe, Shortbow, ArcaneStaff, LightStaff, DarkStaff,
  FireStaff, LightningStaff, IceStaff, ForestStaff, Flintlock, GreatSword, IceSickle, LinenShirt, LinenPants,
  LeatherHelmet, LeatherHood, LeatherChestplate, LeatherGloves, LeatherGreaves, LeatherBoots, IronHelm, IronChainmail,
  IronGauntlets, IronGreaves, IronBoots, ClothHood, ClothRobe, PanzerkamferArmor, Buckler, IronShield,
  PineWood, Pelt, IronOre, Diamond, HealthPotion, StaminaPotion, MagicPotion,
  Antidote, AloeRemedy, Bandage, ParalysisTonic, PoisonedKnife, BearTrap,
  Net, SmokeBomb, ScrollOfInferno, ScrollOfHailStorm, ScrollOfCastShadow, KurtussBrewOfMadness, Meteorite,
  WaterStaff, PanzerianHelm, PanzerianGauntlets, PanzerianGreaves, PanzerianBoots, PanzerianChestplate, NightbladeMask,
} from "../items.js";


export const itemRegistry = {
  "dagger": (config, isRehydrate) => new Dagger(config, isRehydrate),
  "shortsword": (config, isRehydrate) => new ShortSword(config, isRehydrate),
  "spear": (config, isRehydrate) => new Spear(config, isRehydrate),
  "blacksmith hammer": (config, isRehydrate) => new BlacksmithHammer(config, isRehydrate),
  "handaxe": (config, isRehydrate) => new Handaxe(config, isRehydrate),
  "shortbow": (config, isRehydrate) => new Shortbow(config, isRehydrate),
  "arcane staff": (config, isRehydrate) => new ArcaneStaff(config, isRehydrate),
  "light staff": (config, isRehydrate) => new LightStaff(config, isRehydrate),
  "dark staff": (config, isRehydrate) => new DarkStaff(config, isRehydrate),
  "fire staff": (config, isRehydrate) => new FireStaff(config, isRehydrate),
  "lightning staff": (config, isRehydrate) => new LightningStaff(config, isRehydrate),
  "ice staff": (config, isRehydrate) => new IceStaff(config, isRehydrate),
  "water staff": (config, isRehydrate) => new WaterStaff(config, isRehydrate),
  "forest staff": (config, isRehydrate) => new ForestStaff(config, isRehydrate),
  "flintlock": (config, isRehydrate) => new Flintlock(config, isRehydrate),
  "linen shirt": (config, isRehydrate) => new LinenShirt(config, isRehydrate),
  "linen pants": (config, isRehydrate) => new LinenPants(config, isRehydrate),
  "leather helmet": (config, isRehydrate) => new LeatherHelmet(config, isRehydrate),
  "leather hood": (config, isRehydrate) => new LeatherHood(config, isRehydrate),
  "leather chestplate": (config, isRehydrate) => new LeatherChestplate(config, isRehydrate),
  "leather gloves": (config, isRehydrate) => new LeatherGloves(config, isRehydrate),
  "leather greaves": (config, isRehydrate) => new LeatherGreaves(config, isRehydrate),
  "leather boots": (config, isRehydrate) => new LeatherBoots(config, isRehydrate),
  "iron helm": (config, isRehydrate) => new IronHelm(config, isRehydrate),
  "iron chainmail": (config, isRehydrate) => new IronChainmail(config, isRehydrate),
  "iron gauntlets": (config, isRehydrate) => new IronGauntlets(config, isRehydrate),
  "iron greaves": (config, isRehydrate) => new IronGreaves(config, isRehydrate),
  "iron boots": (config, isRehydrate) => new IronBoots(config, isRehydrate),
  "cloth hood": (config, isRehydrate) => new ClothHood(config, isRehydrate),
  "cloth robe": (config, isRehydrate) => new ClothRobe(config, isRehydrate),
  "panzerian helm": (config, isRehydrate) => new PanzerianHelm(config, isRehydrate),
  "panzerian gauntlets": (config, isRehydrate) => new PanzerianGauntlets(config, isRehydrate),
  "panzerian greaves": (config, isRehydrate) => new PanzerianGreaves(config, isRehydrate),
  "panzerian boots": (config, isRehydrate) => new PanzerianBoots(config, isRehydrate),
  "panzerian chestplate": (config, isRehydrate) => new PanzerianChestplate(config, isRehydrate),
  "nightblade mask": (config, isRehydrate) => new NightbladeMask(config, isRehydrate),
  "buckler": (config, isRehydrate) => new Buckler(config, isRehydrate),
  "iron shield": (config, isRehydrate) => new IronShield(config, isRehydrate),
  "panzerkamfer armor": (config, isRehydrate) => new PanzerkamferArmor(config, isRehydrate),
  "greatsword": (config, isRehydrate) => new GreatSword(config, isRehydrate),
  "ice sickle": (config, isRehydrate) => new IceSickle(config, isRehydrate),

  // materials
  "pine wood": (config, isRehydrate) => new PineWood(config, isRehydrate),
  "pelt": (config, isRehydrate) => new Pelt(config, isRehydrate),
  "iron ore": (config, isRehydrate) => new IronOre(config, isRehydrate),
  "diamond": (config, isRehydrate) => new Diamond(config, isRehydrate),

  // consumables
  "health potion": (config, isRehydrate) => new HealthPotion(config, isRehydrate),
  "stamina potion": (config, isRehydrate) => new StaminaPotion(config, isRehydrate),
  "magic potion": (config, isRehydrate) => new MagicPotion(config, isRehydrate),
  "antidote": (config, isRehydrate) => new Antidote(config, isRehydrate),
  "aloe remedy": (config, isRehydrate) => new AloeRemedy(config, isRehydrate),
  "bandage": (config, isRehydrate) => new Bandage(config, isRehydrate),
  "paralysis tonic": (config, isRehydrate) => new ParalysisTonic(config, isRehydrate),
  "poisoned knife": (config, isRehydrate) => new PoisonedKnife(config, isRehydrate),
  "bear trap": (config, isRehydrate) => new BearTrap(config, isRehydrate),
  "net": (config, isRehydrate) => new Net(config, isRehydrate),
  "smoke bomb": (config, isRehydrate) => new SmokeBomb(config, isRehydrate),
  "scroll of inferno": (config, isRehydrate) => new ScrollOfInferno(config, isRehydrate),
  "scroll of hail storm": (config, isRehydrate) => new ScrollOfHailStorm(config, isRehydrate),
  "scroll of cast shadow": (config, isRehydrate) => new ScrollOfCastShadow(config, isRehydrate),
  "kurtuss brew of madness": (config, isRehydrate) => new KurtussBrewOfMadness(config, isRehydrate),
  "meteorite": (config, isRehydrate) => new Meteorite(config, isRehydrate),
};