import {
  Dagger, ShortSword, Spear, BlacksmithHammer, Handaxe, Shortbow, ArcaneStaff, LightStaff, DarkStaff,
  FireStaff, LightningStaff, IceStaff, ForestStaff, Flintlock, GreatSword, IceSickle, LinenShirt, LinenPants,
  LeatherHelmet, LeatherHood, LeatherChestplate, LeatherGloves, LeatherGreaves, LeatherBoots, IronHelm, IronChainmail,
  IronGauntlets, IronGreaves, IronBoots, ClothHood, ClothRobe, PanzerkamferArmor, Buckler, IronShield,
  PineWood, Pelt, IronOre, Diamond, HealthPotion, StaminaPotion, MagicPotion,
  Antidote, AloeRemedy, Bandage, ParalysisTonic, PoisonedKnife, BearTrap,
  Net, SmokeBomb, ScrollOfInferno, ScrollOfHailStorm, ScrollOfCastShadow, KurtussBrewOfMadness, Meteorite,
} from "../items.js";


export const itemRegistry = {
  "dagger": (config, isRehydrate) => new Dagger(config, isRehydrate),
  "shortsword": (config, isRehydrate) => new ShortSword(config, isRehydrate),
  "spear": (config, isRehydrate) => new Spear(config, isRehydrate),
  "blacksmith hammer": (config, isRehydrate) => new BlacksmithHammer(config, isRehydrate),
  "handaxe": (config, isRehydrate) => new Handaxe(config, isRehydrate),
  "shortbow": (config, isRehydrate) => new Shortbow(config, isRehydrate),
  "arcane staff": (config, isRehydrate) => new ArcaneStaff(config, isRehydrate),
  "light staff": (config, isRehydrate) => new LightStaff(config, isRehydrate),
  "dark staff": (config, isRehydrate) => new DarkStaff(config, isRehydrate),
  "fire staff": (config, isRehydrate) => new FireStaff(config, isRehydrate),
  "lightning staff": (config, isRehydrate) => new LightningStaff(config, isRehydrate),
  "ice staff": (config, isRehydrate) => new IceStaff(config, isRehydrate),
  "forest staff": (config, isRehydrate) => new ForestStaff(config, isRehydrate),
  "flintlock": (config, isRehydrate) => new Flintlock(config, isRehydrate),
  "linen shirt": (config, isRehydrate) => new LinenShirt(config, isRehydrate),
  "linen pants": (config, isRehydrate) => new LinenPants(config, isRehydrate),
  "leather helmet": (config, isRehydrate) => new LeatherHelmet(config, isRehydrate),
  "leather hood": (config, isRehydrate) => new LeatherHood(config, isRehydrate),
  "leather chestplate": (config, isRehydrate) => new LeatherChestplate(config, isRehydrate),
  "leather gloves": (config, isRehydrate) => new LeatherGloves(config, isRehydrate),
  "leather greaves": (config, isRehydrate) => new LeatherGreaves(config, isRehydrate),
  "leather boots": (config, isRehydrate) => new LeatherBoots(config, isRehydrate),
  "iron helm": (config, isRehydrate) => new IronHelm(config, isRehydrate),
  "iron chainmail": (config, isRehydrate) => new IronChainmail(config, isRehydrate),
  "iron gauntlets": (config, isRehydrate) => new IronGauntlets(config, isRehydrate),
  "iron greaves": (config, isRehydrate) => new IronGreaves(config, isRehydrate),
  "iron boots": (config, isRehydrate) => new IronBoots(config, isRehydrate),
  "cloth hood": (config, isRehydrate) => new ClothHood(config, isRehydrate),
  "cloth robe": (config, isRehydrate) => new ClothRobe(config, isRehydrate),
  "buckler": (config, isRehydrate) => new Buckler(config, isRehydrate),
  "iron shield": (config, isRehydrate) => new IronShield(config, isRehydrate),
  "panzerkamfer armor": (config, isRehydrate) => new PanzerkamferArmor(config, isRehydrate),
  "greatsword": (config, isRehydrate) => new GreatSword(config, isRehydrate),
  "ice sickle": (config, isRehydrate) => new IceSickle(config, isRehydrate),

  // materials
  "pine wood": () => new PineWood(),
  "pelt": () => new Pelt(),
  "iron ore": () => new IronOre(),
  "diamond": () => new Diamond(),

  // consumables
  "health potion": () => new HealthPotion(),
  "stamina potion": () => new StaminaPotion(),
  "magic potion": () => new MagicPotion(),
  "antidote": () => new Antidote(),
  "aloe remedy": () => new AloeRemedy(),
  "bandage": () => new Bandage(),
  "paralysis tonic": () => new ParalysisTonic(),
  "poisoned knife": () => new PoisonedKnife(),
  "bear trap": () => new BearTrap(),
  "net": () => new Net(),
  "smoke bomb": () => new SmokeBomb(),
  "scroll of inferno": () => new ScrollOfInferno(),
  "scroll of hail storm": () => new ScrollOfHailStorm(),
  "scroll of cast shadow": () => new ScrollOfCastShadow(),
  "kurtuss brew of madness": () => new KurtussBrewOfMadness(),
  "meteorite": () => new Meteorite(),
};