import {
  Poison,
  Burn,
  Bleed,
  Bind,
  Paralyzed,
  Frozen,
  Shielded,
  KnockedDown,
  Flying,
  InstaDeath,
  Blessed,
  Cursed,
  BearTrapSet,
  SoulLinked,
  Polymorphed,
  PhysicalAttackBuff,
  PhysicalAttackDebuff,
  MagicalAttackBuff,
  MagicalAttackDebuff,
  PhysicalDefenseBuff,
  PhysicalDefenseDebuff,
  EvasionBuff,
} from "../statusEffects.js";

export const statusEffectRegistry = {
  "poison": (config) => new Poison(config),
  "burn": (config) => new Burn(config),
  "bleed": (config) => new Bleed(config),
  "bind": (config) => new Bind(config),
  "paralyzed": (config) => new Paralyzed(config),
  "frozen": (config) => new Frozen(config),
  "shielded": (config) => new Shielded(config),
  "knocked down": (config) => new KnockedDown(config),
  "flying": (config) => new Flying(config),
  "insta death": (config) => new InstaDeath(config),
  "blessed": (config) => new Blessed(config),
  "cursed": (config) => new Cursed(config),
  "bear trap set": (config) => new BearTrapSet(config),
  "soul linked": (config) => new SoulLinked(config),
  "polymorphed": (config) => new Polymorphed(config),
  "physical attack buff": (config) => new PhysicalAttackBuff(config),
  "physical attack debuff": (config) => new PhysicalAttackDebuff(config),
  "magical attack buff": (config) => new MagicalAttackBuff(config),
  "magical attack debuff": (config) => new MagicalAttackDebuff(config),
  "physical defense buff": (config) => new PhysicalDefenseBuff(config),
  "physical defense debuff": (config) => new PhysicalDefenseDebuff(config),
  "evasion buff": (config) => new EvasionBuff(config),
};